services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasktracker
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d tasktracker" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=tasktracker
      - DATABASE_URL=postgres://user:password@db:5432/tasktracker?sslmode=disable
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
