services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasktracker
    ports:
      - "8100:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
