// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MemberRole string

const (
	MemberRoleViewer        MemberRole = "viewer"
	MemberRoleMember        MemberRole = "member"
	MemberRoleAdministrator MemberRole = "administrator"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole
	Valid      bool // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type TaskStatus string

const (
	TaskStatusToDo       TaskStatus = "to_do"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusDone       TaskStatus = "done"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus
	Valid      bool // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type Board struct {
	ID          pgtype.UUID
	Name        pgtype.Text
	WorkspaceID pgtype.UUID
	CreatedAt   pgtype.Timestamp
	CreatedBy   pgtype.UUID
}

type Task struct {
	ID          pgtype.UUID
	BoardID     pgtype.UUID
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	AssignedID  pgtype.UUID
	Name        pgtype.Text
	Description pgtype.Text
	Status      NullTaskStatus
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}

type Workspace struct {
	ID        pgtype.UUID
	Title     pgtype.Text
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamp
}

type WorkspaceMember struct {
	UserID      pgtype.UUID
	WorkspaceID pgtype.UUID
	Role        NullMemberRole
}
