// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MemberRole string

const (
	MemberRoleViewer        MemberRole = "viewer"
	MemberRoleMember        MemberRole = "member"
	MemberRoleAdministrator MemberRole = "administrator"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole
	Valid      bool // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type TaskStatus string

const (
	TaskStatusToDo       TaskStatus = "to_do"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusDone       TaskStatus = "done"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus
	Valid      bool // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type Board struct {
	BoardID     uuid.UUID
	Title       pgtype.Text
	WorkspaceID *uuid.UUID
	CreatedAt   pgtype.Timestamp
	CreatedBy   *uuid.UUID
}

type EmailVerificationToken struct {
	TokenID   uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type PasswordResetToken struct {
	TokenID   uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type Task struct {
	TaskID      int32
	BoardID     *uuid.UUID
	CreatedBy   *uuid.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	AssignedID  *uuid.UUID
	Title       pgtype.Text
	Description pgtype.Text
	Status      NullTaskStatus
}

type TaskBlockpoint struct {
	TaskID          int32
	BlockedByTaskID int32
}

type User struct {
	UserID        uuid.UUID
	Email         string
	Username      string
	PasswordHash  string
	EmailVerified bool
	CreatedAt     pgtype.Timestamp
}

type Workspace struct {
	WorkspaceID uuid.UUID
	Title       pgtype.Text
	CreatedBy   *uuid.UUID
	CreatedAt   pgtype.Timestamp
}

type WorkspaceMember struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Role        NullMemberRole
}
