// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBlockpoint = `-- name: AddBlockpoint :exec
INSERT INTO task_blockpoints (task_id, blocked_by_task_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddBlockpointParams struct {
	TaskID          int32
	BlockedByTaskID int32
}

func (q *Queries) AddBlockpoint(ctx context.Context, arg AddBlockpointParams) error {
	_, err := q.db.Exec(ctx, addBlockpoint, arg.TaskID, arg.BlockedByTaskID)
	return err
}

const addMember = `-- name: AddMember :one
INSERT INTO workspace_members (user_id, workspace_id, role)
VALUES($1, $2, $3)
RETURNING user_id
`

type AddMemberParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Role        NullMemberRole
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addMember, arg.UserID, arg.WorkspaceID, arg.Role)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const changePassword = `-- name: ChangePassword :exec
UPDATE users 
SET password_hash = $1
WHERE user_id = $2
`

type ChangePasswordParams struct {
	PasswordHash string
	UserID       uuid.UUID
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) error {
	_, err := q.db.Exec(ctx, changePassword, arg.PasswordHash, arg.UserID)
	return err
}

const changeTaskStatus = `-- name: ChangeTaskStatus :exec
UPDATE tasks
SET status = $1
WHERE task_id = $2
`

type ChangeTaskStatusParams struct {
	Status NullTaskStatus
	TaskID int32
}

func (q *Queries) ChangeTaskStatus(ctx context.Context, arg ChangeTaskStatusParams) error {
	_, err := q.db.Exec(ctx, changeTaskStatus, arg.Status, arg.TaskID)
	return err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (title, workspace_id, created_at, created_by)
VALUES($1, $2, NOW(), $3)
RETURNING board_id
`

type CreateBoardParams struct {
	Title       pgtype.Text
	WorkspaceID *uuid.UUID
	CreatedBy   *uuid.UUID
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.Title, arg.WorkspaceID, arg.CreatedBy)
	var board_id uuid.UUID
	err := row.Scan(&board_id)
	return board_id, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING token_id
`

type CreateEmailVerificationTokenParams struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var token_id uuid.UUID
	err := row.Scan(&token_id)
	return token_id, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING token_id
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var token_id uuid.UUID
	err := row.Scan(&token_id)
	return token_id, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (board_id, created_by, title, description, assigned_id)
VALUES($1, $2, $3, $4, $5)
RETURNING task_id
`

type CreateTaskParams struct {
	BoardID     *uuid.UUID
	CreatedBy   *uuid.UUID
	Title       pgtype.Text
	Description pgtype.Text
	AssignedID  *uuid.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.BoardID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.AssignedID,
	)
	var task_id int32
	err := row.Scan(&task_id)
	return task_id, err
}

const createUser = `-- name: CreateUser :one


INSERT INTO users (email, username, password_hash, email_verified, created_at)
VALUES($1, $2, $3, FALSE, NOW())
RETURNING user_id
`

type CreateUserParams struct {
	Email        string
	Username     string
	PasswordHash string
}

// CRUD functions query
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.PasswordHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (created_at, title, created_by)
VALUES(NOW(), $1, $2)
RETURNING workspace_id
`

type CreateWorkspaceParams struct {
	Title     pgtype.Text
	CreatedBy *uuid.UUID
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Title, arg.CreatedBy)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const deleteAllBlockpointsForTask = `-- name: DeleteAllBlockpointsForTask :exec
DELETE FROM task_blockpoints
WHERE task_id = $1
`

func (q *Queries) DeleteAllBlockpointsForTask(ctx context.Context, taskID int32) error {
	_, err := q.db.Exec(ctx, deleteAllBlockpointsForTask, taskID)
	return err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards
WHERE board_id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, boardID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoard, boardID)
	return err
}

const deleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
DELETE FROM email_verification_tokens
WHERE token = $1
`

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationToken, token)
	return err
}

const deleteEmailVerificationTokensByUserID = `-- name: DeleteEmailVerificationTokensByUserID :exec
DELETE FROM email_verification_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerificationTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokensByUserID, userID)
	return err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM password_reset_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM password_reset_tokens
WHERE token = $1
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deletePasswordResetToken, token)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE task_id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, taskID int32) error {
	_, err := q.db.Exec(ctx, deleteTask, taskID)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces
WHERE workspace_id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, workspaceID)
	return err
}

const editBoard = `-- name: EditBoard :exec
UPDATE boards
SET title = $1
WHERE board_id = $2
`

type EditBoardParams struct {
	Title   pgtype.Text
	BoardID uuid.UUID
}

func (q *Queries) EditBoard(ctx context.Context, arg EditBoardParams) error {
	_, err := q.db.Exec(ctx, editBoard, arg.Title, arg.BoardID)
	return err
}

const editWorkspace = `-- name: EditWorkspace :exec
UPDATE workspaces 
SET title = $1
WHERE workspace_id = $2
`

type EditWorkspaceParams struct {
	Title       pgtype.Text
	WorkspaceID uuid.UUID
}

func (q *Queries) EditWorkspace(ctx context.Context, arg EditWorkspaceParams) error {
	_, err := q.db.Exec(ctx, editWorkspace, arg.Title, arg.WorkspaceID)
	return err
}

const getEmailVerificationToken = `-- name: GetEmailVerificationToken :one
SELECT token_id, user_id, token, expires_at, created_at
FROM email_verification_tokens
WHERE token = $1
`

func (q *Queries) GetEmailVerificationToken(ctx context.Context, token string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationToken, token)
	var i EmailVerificationToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberRoleById = `-- name: GetMemberRoleById :one
SELECT role
FROM workspace_members
WHERE user_id = $1
`

func (q *Queries) GetMemberRoleById(ctx context.Context, userID uuid.UUID) (NullMemberRole, error) {
	row := q.db.QueryRow(ctx, getMemberRoleById, userID)
	var role NullMemberRole
	err := row.Scan(&role)
	return role, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT token_id, user_id, token, expires_at, created_at
FROM password_reset_tokens
WHERE token = $1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskBlockpoints = `-- name: GetTaskBlockpoints :many
SELECT blocked_by_task_id
FROM task_blockpoints
WHERE task_id = $1
`

func (q *Queries) GetTaskBlockpoints(ctx context.Context, taskID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getTaskBlockpoints, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var blocked_by_task_id int32
		if err := rows.Scan(&blocked_by_task_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_by_task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksFromBoard = `-- name: GetTasksFromBoard :many
SELECT task_id, board_id, created_at, created_by, updated_at, assigned_id, title, description, status
FROM tasks 
WHERE board_id = $1
ORDER BY created_at ASC
`

type GetTasksFromBoardRow struct {
	TaskID      int32
	BoardID     *uuid.UUID
	CreatedAt   pgtype.Timestamp
	CreatedBy   *uuid.UUID
	UpdatedAt   pgtype.Timestamp
	AssignedID  *uuid.UUID
	Title       pgtype.Text
	Description pgtype.Text
	Status      NullTaskStatus
}

func (q *Queries) GetTasksFromBoard(ctx context.Context, boardID *uuid.UUID) ([]GetTasksFromBoardRow, error) {
	rows, err := q.db.Query(ctx, getTasksFromBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTasksFromBoardRow
	for rows.Next() {
		var i GetTasksFromBoardRow
		if err := rows.Scan(
			&i.TaskID,
			&i.BoardID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.AssignedID,
			&i.Title,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, email, username, password_hash, email_verified, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT user_id, email, username, password_hash, email_verified, created_at
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserById(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUsersWorkspace = `-- name: GetUsersWorkspace :many
SELECT workspace_id, title, created_by, created_at
FROM workspaces
WHERE created_by = $1
ORDER BY created_at ASC
`

func (q *Queries) GetUsersWorkspace(ctx context.Context, createdBy *uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getUsersWorkspace, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceBoards = `-- name: GetWorkspaceBoards :many
SELECT board_id, title, workspace_id, created_at, created_by
FROM boards
WHERE workspace_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetWorkspaceBoards(ctx context.Context, workspaceID *uuid.UUID) ([]Board, error) {
	rows, err := q.db.Query(ctx, getWorkspaceBoards, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.BoardID,
			&i.Title,
			&i.WorkspaceID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceById = `-- name: GetWorkspaceById :one
SELECT workspace_id, title, created_at, created_by
FROM workspaces
WHERE workspace_id = $1
`

type GetWorkspaceByIdRow struct {
	WorkspaceID uuid.UUID
	Title       pgtype.Text
	CreatedAt   pgtype.Timestamp
	CreatedBy   *uuid.UUID
}

func (q *Queries) GetWorkspaceById(ctx context.Context, workspaceID uuid.UUID) (GetWorkspaceByIdRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceById, workspaceID)
	var i GetWorkspaceByIdRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.Title,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const kickUser = `-- name: KickUser :exec
DELETE FROM workspace_members
WHERE user_id = $1
`

func (q *Queries) KickUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, kickUser, userID)
	return err
}

const manageMember = `-- name: ManageMember :exec
UPDATE workspace_members
SET role = $1
WHERE user_id = $2
`

type ManageMemberParams struct {
	Role   NullMemberRole
	UserID uuid.UUID
}

func (q *Queries) ManageMember(ctx context.Context, arg ManageMemberParams) error {
	_, err := q.db.Exec(ctx, manageMember, arg.Role, arg.UserID)
	return err
}

const removeBlockpoint = `-- name: RemoveBlockpoint :exec
DELETE FROM task_blockpoints
WHERE task_id = $1 AND blocked_by_task_id = $2
`

type RemoveBlockpointParams struct {
	TaskID          int32
	BlockedByTaskID int32
}

func (q *Queries) RemoveBlockpoint(ctx context.Context, arg RemoveBlockpointParams) error {
	_, err := q.db.Exec(ctx, removeBlockpoint, arg.TaskID, arg.BlockedByTaskID)
	return err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = TRUE WHERE user_id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setEmailVerified, userID)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET title = $2, description = $3, assigned_id = $4, status = $5, updated_at = NOW()
WHERE task_id = $1
`

type UpdateTaskParams struct {
	TaskID      int32
	Title       pgtype.Text
	Description pgtype.Text
	AssignedID  *uuid.UUID
	Status      NullTaskStatus
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.AssignedID,
		arg.Status,
	)
	return err
}
