// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBlockpoint = `-- name: AddBlockpoint :exec
INSERT INTO task_blockpoints (task_id, blocked_by_task_id) 
VALUES ($1, $2) 
ON CONFLICT DO NOTHING
`

type AddBlockpointParams struct {
	TaskID          int32
	BlockedByTaskID int32
}

func (q *Queries) AddBlockpoint(ctx context.Context, arg AddBlockpointParams) error {
	_, err := q.db.Exec(ctx, addBlockpoint, arg.TaskID, arg.BlockedByTaskID)
	return err
}

const addMember = `-- name: AddMember :one
INSERT INTO workspace_members (user_id, workspace_id, role) 
VALUES($1, $2, $3) 
RETURNING user_id
`

type AddMemberParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Role        NullMemberRole
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addMember, arg.UserID, arg.WorkspaceID, arg.Role)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const changePassword = `-- name: ChangePassword :exec
UPDATE users SET password_hash = $1 WHERE user_id = $2
`

type ChangePasswordParams struct {
	PasswordHash string
	UserID       uuid.UUID
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) error {
	_, err := q.db.Exec(ctx, changePassword, arg.PasswordHash, arg.UserID)
	return err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (title, workspace_id, created_at, created_by) 
VALUES($1, $2, NOW(), $3) 
RETURNING board_id
`

type CreateBoardParams struct {
	Title       pgtype.Text
	WorkspaceID *uuid.UUID
	CreatedBy   *uuid.UUID
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.Title, arg.WorkspaceID, arg.CreatedBy)
	var board_id uuid.UUID
	err := row.Scan(&board_id)
	return board_id, err
}

const createColumn = `-- name: CreateColumn :one

INSERT INTO columns (board_id, name, position, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING column_id, board_id, name, position, created_at
`

type CreateColumnParams struct {
	BoardID  uuid.UUID
	Name     string
	Position int32
}

// =========================================================================
// NEW NEW NEW: COLUMNS CRUD (Your Dynamic Enum Management)
// =========================================================================
func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRow(ctx, createColumn, arg.BoardID, arg.Name, arg.Position)
	var i Column
	err := row.Scan(
		&i.ColumnID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO comments (board_id, author_id, content)
VALUES ($1, $2, $3)
RETURNING comment_id, board_id, author_id, sent_at, content
`

type CreateCommentParams struct {
	BoardID  *uuid.UUID
	AuthorID *uuid.UUID
	Content  pgtype.Text
}

// =========================================================================
// COMMENTS CRUD
// =========================================================================
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.BoardID, arg.AuthorID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.CommentID,
		&i.BoardID,
		&i.AuthorID,
		&i.SentAt,
		&i.Content,
	)
	return i, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (user_id, token, expires_at) 
VALUES ($1, $2, $3) 
RETURNING token_id
`

type CreateEmailVerificationTokenParams struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var token_id uuid.UUID
	err := row.Scan(&token_id)
	return token_id, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one

INSERT INTO password_reset_tokens (user_id, token, expires_at) 
VALUES ($1, $2, $3) 
RETURNING token_id
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
}

// =========================================================================
// TOKENS & UTILITIES (Unchanged)
// =========================================================================
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var token_id uuid.UUID
	err := row.Scan(&token_id)
	return token_id, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (column_id, created_by, title, description, assigned_id, start_date, due_date) 
VALUES($1, $2, $3, $4, $5, $6, $7) 
RETURNING task_id
`

type CreateTaskParams struct {
	ColumnID    *uuid.UUID
	CreatedBy   *uuid.UUID
	Title       pgtype.Text
	Description pgtype.Text
	AssignedID  *uuid.UUID
	StartDate   pgtype.Date
	DueDate     pgtype.Date
}

// =========================================================================
// REFACTORED: TASKS CRUD (Uses column_id instead of board_id/status enum)
// =========================================================================
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ColumnID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.AssignedID,
		arg.StartDate,
		arg.DueDate,
	)
	var task_id int32
	err := row.Scan(&task_id)
	return task_id, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, username, password_hash, email_verified, created_at) 
VALUES($1, $2, $3, FALSE, NOW()) 
RETURNING user_id
`

type CreateUserParams struct {
	Email        string
	Username     string
	PasswordHash string
}

// CRUD functions query
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.PasswordHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (created_at, title, created_by) 
VALUES(NOW(), $1, $2) 
RETURNING workspace_id
`

type CreateWorkspaceParams struct {
	Title     pgtype.Text
	CreatedBy *uuid.UUID
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Title, arg.CreatedBy)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const deleteAllBlockpointsForTask = `-- name: DeleteAllBlockpointsForTask :exec
DELETE FROM task_blockpoints WHERE task_id = $1
`

func (q *Queries) DeleteAllBlockpointsForTask(ctx context.Context, taskID int32) error {
	_, err := q.db.Exec(ctx, deleteAllBlockpointsForTask, taskID)
	return err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards WHERE board_id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, boardID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoard, boardID)
	return err
}

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM columns WHERE column_id = $1
`

func (q *Queries) DeleteColumn(ctx context.Context, columnID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteColumn, columnID)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE comment_id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, commentID int32) error {
	_, err := q.db.Exec(ctx, deleteComment, commentID)
	return err
}

const deleteCommentsByBoard = `-- name: DeleteCommentsByBoard :exec
DELETE FROM comments WHERE board_id = $1
`

func (q *Queries) DeleteCommentsByBoard(ctx context.Context, boardID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommentsByBoard, boardID)
	return err
}

const deleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
DELETE FROM email_verification_tokens WHERE token = $1
`

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationToken, token)
	return err
}

const deleteEmailVerificationTokensByUserID = `-- name: DeleteEmailVerificationTokensByUserID :exec
DELETE FROM email_verification_tokens WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerificationTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokensByUserID, userID)
	return err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM password_reset_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM password_reset_tokens WHERE token = $1
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deletePasswordResetToken, token)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE task_id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, taskID int32) error {
	_, err := q.db.Exec(ctx, deleteTask, taskID)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE workspace_id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, workspaceID)
	return err
}

const editBoard = `-- name: EditBoard :exec
UPDATE boards SET title = $1 WHERE board_id = $2
`

type EditBoardParams struct {
	Title   pgtype.Text
	BoardID uuid.UUID
}

func (q *Queries) EditBoard(ctx context.Context, arg EditBoardParams) error {
	_, err := q.db.Exec(ctx, editBoard, arg.Title, arg.BoardID)
	return err
}

const editColumn = `-- name: EditColumn :exec
UPDATE columns 
SET name = $1, position = $2 
WHERE column_id = $3
`

type EditColumnParams struct {
	Name     string
	Position int32
	ColumnID uuid.UUID
}

func (q *Queries) EditColumn(ctx context.Context, arg EditColumnParams) error {
	_, err := q.db.Exec(ctx, editColumn, arg.Name, arg.Position, arg.ColumnID)
	return err
}

const editWorkspace = `-- name: EditWorkspace :exec
UPDATE workspaces SET title = $1 WHERE workspace_id = $2
`

type EditWorkspaceParams struct {
	Title       pgtype.Text
	WorkspaceID uuid.UUID
}

func (q *Queries) EditWorkspace(ctx context.Context, arg EditWorkspaceParams) error {
	_, err := q.db.Exec(ctx, editWorkspace, arg.Title, arg.WorkspaceID)
	return err
}

const getAllUserWorkspaces = `-- name: GetAllUserWorkspaces :many
SELECT w.workspace_id, w.title, w.created_by, w.created_at
FROM workspaces w
WHERE w.created_by = $1
UNION
SELECT w.workspace_id, w.title, w.created_by, w.created_at
FROM workspaces w
JOIN workspace_members wm ON w.workspace_id = wm.workspace_id
WHERE wm.user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetAllUserWorkspaces(ctx context.Context, createdBy *uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getAllUserWorkspaces, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getColumnsFromBoard = `-- name: GetColumnsFromBoard :many
SELECT column_id, board_id, name, position, created_at
FROM columns
WHERE board_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) GetColumnsFromBoard(ctx context.Context, boardID uuid.UUID) ([]Column, error) {
	rows, err := q.db.Query(ctx, getColumnsFromBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Column
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ColumnID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentById = `-- name: GetCommentById :one
SELECT comment_id, board_id, author_id, sent_at, content
FROM comments
WHERE comment_id = $1
`

func (q *Queries) GetCommentById(ctx context.Context, commentID int32) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentById, commentID)
	var i Comment
	err := row.Scan(
		&i.CommentID,
		&i.BoardID,
		&i.AuthorID,
		&i.SentAt,
		&i.Content,
	)
	return i, err
}

const getCommentsByBoard = `-- name: GetCommentsByBoard :many
SELECT comment_id, board_id, author_id, sent_at, content
FROM comments
WHERE board_id = $1
ORDER BY sent_at ASC
`

func (q *Queries) GetCommentsByBoard(ctx context.Context, boardID *uuid.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getCommentsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.CommentID,
			&i.BoardID,
			&i.AuthorID,
			&i.SentAt,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailVerificationToken = `-- name: GetEmailVerificationToken :one
SELECT token_id, user_id, token, expires_at, created_at 
FROM email_verification_tokens 
WHERE token = $1
`

func (q *Queries) GetEmailVerificationToken(ctx context.Context, token string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationToken, token)
	var i EmailVerificationToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberRoleById = `-- name: GetMemberRoleById :one
SELECT role FROM workspace_members WHERE user_id = $1
`

func (q *Queries) GetMemberRoleById(ctx context.Context, userID uuid.UUID) (NullMemberRole, error) {
	row := q.db.QueryRow(ctx, getMemberRoleById, userID)
	var role NullMemberRole
	err := row.Scan(&role)
	return role, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT token_id, user_id, token, expires_at, created_at 
FROM password_reset_tokens 
WHERE token = $1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskBlockpoints = `-- name: GetTaskBlockpoints :many
SELECT blocked_by_task_id FROM task_blockpoints WHERE task_id = $1
`

func (q *Queries) GetTaskBlockpoints(ctx context.Context, taskID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getTaskBlockpoints, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var blocked_by_task_id int32
		if err := rows.Scan(&blocked_by_task_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_by_task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksFromBoard = `-- name: GetTasksFromBoard :many
SELECT t.task_id, t.column_id, t.created_at, t.created_by, t.updated_at, t.assigned_id, t.title, t.description, t.start_date, t.due_date
FROM tasks t
JOIN columns c ON t.column_id = c.column_id
WHERE c.board_id = $1 
ORDER BY t.created_at ASC
`

type GetTasksFromBoardRow struct {
	TaskID      int32
	ColumnID    *uuid.UUID
	CreatedAt   pgtype.Timestamp
	CreatedBy   *uuid.UUID
	UpdatedAt   pgtype.Timestamp
	AssignedID  *uuid.UUID
	Title       pgtype.Text
	Description pgtype.Text
	StartDate   pgtype.Date
	DueDate     pgtype.Date
}

// Uses a JOIN to fetch all tasks for a board now that board_id is gone from tasks table
func (q *Queries) GetTasksFromBoard(ctx context.Context, boardID uuid.UUID) ([]GetTasksFromBoardRow, error) {
	rows, err := q.db.Query(ctx, getTasksFromBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTasksFromBoardRow
	for rows.Next() {
		var i GetTasksFromBoardRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ColumnID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.AssignedID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksFromColumn = `-- name: GetTasksFromColumn :many
SELECT task_id, column_id, created_at, created_by, updated_at, assigned_id, title, description 
FROM tasks 
WHERE column_id = $1 
ORDER BY created_at ASC
`

type GetTasksFromColumnRow struct {
	TaskID      int32
	ColumnID    *uuid.UUID
	CreatedAt   pgtype.Timestamp
	CreatedBy   *uuid.UUID
	UpdatedAt   pgtype.Timestamp
	AssignedID  *uuid.UUID
	Title       pgtype.Text
	Description pgtype.Text
}

// Keep this only if you intentionally want to paginate or lazy-load individual lists
func (q *Queries) GetTasksFromColumn(ctx context.Context, columnID *uuid.UUID) ([]GetTasksFromColumnRow, error) {
	rows, err := q.db.Query(ctx, getTasksFromColumn, columnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTasksFromColumnRow
	for rows.Next() {
		var i GetTasksFromColumnRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ColumnID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.AssignedID,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, email, username, password_hash, email_verified, created_at 
FROM users 
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT user_id, email, username, password_hash, email_verified, created_at 
FROM users 
WHERE user_id = $1
`

func (q *Queries) GetUserById(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUsersWorkspace = `-- name: GetUsersWorkspace :many
SELECT workspace_id, title, created_by, created_at 
FROM workspaces 
WHERE created_by = $1 
ORDER BY created_at ASC
`

func (q *Queries) GetUsersWorkspace(ctx context.Context, createdBy *uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getUsersWorkspace, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceBoards = `-- name: GetWorkspaceBoards :many
SELECT board_id, title, workspace_id, created_at, created_by 
FROM boards 
WHERE workspace_id = $1 
ORDER BY created_at ASC
`

func (q *Queries) GetWorkspaceBoards(ctx context.Context, workspaceID *uuid.UUID) ([]Board, error) {
	rows, err := q.db.Query(ctx, getWorkspaceBoards, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.BoardID,
			&i.Title,
			&i.WorkspaceID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceById = `-- name: GetWorkspaceById :one
SELECT workspace_id, title, created_at, created_by 
FROM workspaces 
WHERE workspace_id = $1
`

type GetWorkspaceByIdRow struct {
	WorkspaceID uuid.UUID
	Title       pgtype.Text
	CreatedAt   pgtype.Timestamp
	CreatedBy   *uuid.UUID
}

func (q *Queries) GetWorkspaceById(ctx context.Context, workspaceID uuid.UUID) (GetWorkspaceByIdRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceById, workspaceID)
	var i GetWorkspaceByIdRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.Title,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getWorkspaceMembers = `-- name: GetWorkspaceMembers :many
SELECT wm.user_id, wm.workspace_id, wm.role, u.username, u.email
FROM workspace_members wm
JOIN users u ON wm.user_id = u.user_id
WHERE wm.workspace_id = $1
ORDER BY wm.role DESC, u.username ASC
`

type GetWorkspaceMembersRow struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Role        NullMemberRole
	Username    string
	Email       string
}

func (q *Queries) GetWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]GetWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspaceMembersRow
	for rows.Next() {
		var i GetWorkspaceMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.WorkspaceID,
			&i.Role,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kickUser = `-- name: KickUser :exec
DELETE FROM workspace_members WHERE user_id = $1
`

func (q *Queries) KickUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, kickUser, userID)
	return err
}

const manageMember = `-- name: ManageMember :exec
UPDATE workspace_members SET role = $1 WHERE user_id = $2
`

type ManageMemberParams struct {
	Role   NullMemberRole
	UserID uuid.UUID
}

func (q *Queries) ManageMember(ctx context.Context, arg ManageMemberParams) error {
	_, err := q.db.Exec(ctx, manageMember, arg.Role, arg.UserID)
	return err
}

const moveTaskToColumn = `-- name: MoveTaskToColumn :exec
UPDATE tasks SET column_id = $1, updated_at = NOW() WHERE task_id = $2
`

type MoveTaskToColumnParams struct {
	ColumnID *uuid.UUID
	TaskID   int32
}

func (q *Queries) MoveTaskToColumn(ctx context.Context, arg MoveTaskToColumnParams) error {
	_, err := q.db.Exec(ctx, moveTaskToColumn, arg.ColumnID, arg.TaskID)
	return err
}

const removeBlockpoint = `-- name: RemoveBlockpoint :exec
DELETE FROM task_blockpoints WHERE task_id = $1 AND blocked_by_task_id = $2
`

type RemoveBlockpointParams struct {
	TaskID          int32
	BlockedByTaskID int32
}

func (q *Queries) RemoveBlockpoint(ctx context.Context, arg RemoveBlockpointParams) error {
	_, err := q.db.Exec(ctx, removeBlockpoint, arg.TaskID, arg.BlockedByTaskID)
	return err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = TRUE WHERE user_id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setEmailVerified, userID)
	return err
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments SET content = $1 WHERE comment_id = $2
`

type UpdateCommentParams struct {
	Content   pgtype.Text
	CommentID int32
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.Exec(ctx, updateComment, arg.Content, arg.CommentID)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks 
SET title = $2, description = $3, assigned_id = $4, column_id = $5, start_date = $6, due_date = $7, updated_at = NOW() 
WHERE task_id = $1
`

type UpdateTaskParams struct {
	TaskID      int32
	Title       pgtype.Text
	Description pgtype.Text
	AssignedID  *uuid.UUID
	ColumnID    *uuid.UUID
	StartDate   pgtype.Date
	DueDate     pgtype.Date
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.AssignedID,
		arg.ColumnID,
		arg.StartDate,
		arg.DueDate,
	)
	return err
}
