// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBoard = `-- name: createBoard :one
INSERT INTO boards (name, workspace_id, created_at, created_by)
VALUES($1, $2, NOW(), $3)
RETURNING id
`

type createBoardParams struct {
	Name        pgtype.Text
	WorkspaceID pgtype.UUID
	CreatedBy   pgtype.UUID
}

func (q *Queries) createBoard(ctx context.Context, arg createBoardParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.Name, arg.WorkspaceID, arg.CreatedBy)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createTask = `-- name: createTask :one
INSERT INTO tasks (created_at, name, description, assigned_id)
VALUES(NOW(), $1, $2, $3)
RETURNING id
`

type createTaskParams struct {
	Name        pgtype.Text
	Description pgtype.Text
	AssignedID  pgtype.UUID
}

func (q *Queries) createTask(ctx context.Context, arg createTaskParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Name, arg.Description, arg.AssignedID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteTask = `-- name: deleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) deleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getBoardTasks = `-- name: getBoardTasks :many

SELECT id
FROM tasks 
WHERE board_id = $1
ORDER BY created_at ASC
`

// CRUD functions query
func (q *Queries) getBoardTasks(ctx context.Context, boardID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getBoardTasks, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceBoards = `-- name: getWorkspaceBoards :many
SELECT id
FROM boards
WHERE workspace_id = $1
ORDER BY created_at ASC
`

func (q *Queries) getWorkspaceBoards(ctx context.Context, workspaceID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getWorkspaceBoards, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: updateTask :exec
UPDATE tasks
SET updated_at = NOW(), name = $2, description = $3, assigned_id = $4, status = $5
WHERE id = $1
`

type updateTaskParams struct {
	ID          pgtype.UUID
	Name        pgtype.Text
	Description pgtype.Text
	AssignedID  pgtype.UUID
	Status      NullTaskStatus
}

func (q *Queries) updateTask(ctx context.Context, arg updateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AssignedID,
		arg.Status,
	)
	return err
}
